language: elixir
elixir:
  - 1.9.4
env:
  - MIX_ENV=test
script:
  - mix deps.get
  - mix compile
  - mix test
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
cache:
  directories:
    - _build
    - deps
